lenguage: python

python:
  - '3.9'
install:
  - pip install -r requirements.txt
git:
  depth: 3
  
script:
  - pytest test.py
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-page
  commit_message: 'Deploy del proyecto'
  on:
    branch: main