lenguage: python

python:
  - '3.9'
install:
  - pip install -r requirements.txt
git:
  depth: 3

edge: true
  
script:
  - pytest test.py
deploy:
  provider: heroku
  api_key: 3d62ba6b-adfe-4f44-8ee3-8d3bf10f2b47
  app: test-ci-cd
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: /
  target_branch: test-travis-heroku
  commit_message: 'Deploy del proyecto'
  on:
    branch: test-travis-heroku
    repo: emmanuelepp/test-ci-cd